# Generated by Django 4.2.6 on 2023-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='infoText',
            field=models.TextField(default='no info'),
        ),
    ]
