# Generated by Django 4.2.6 on 2023-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
